name: Test Workflow
on:
  push:
    branches:
      - main

jobs:
  check-tests:
    runs-on: ubuntu-latest
    strategy:
      # Matrika z python različicami od 3.7 -> 3.11
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.11]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Check if test scripts exist
        run: |
          if [ -f mytest.py ]; then
            echo "mytest.py" > test_results.txt
          else
            echo "Test script not found" > napaka.txt
          fi
        shell: bash

      - name: Store test results artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: test_results
          path: test_results.txt
          # Če ustrezna datoteka ni bila najdena, se kliče error
          if-no-files-found: error

  run-tests:
    runs-on: ubuntu-latest
    needs: check-tests
    # Če ni prišlo do napak, se nadaljuje 2. posel
    if: failure() != 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download test results artifacts
        uses: actions/download-artifact@v2
        with:
          name: test_results
          path: test_results.txt

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

        # Namesti module np, openvc, pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy pytest opencv-python
        shell: bash

        # Zažene mytest.py
      - name: Run tests
        run: python mytest.py

      - name: Read error file
        run: | 
          if [ -f napaka.txt ]; then
            cat napaka.txt
          fi
