name: Deploy Workflow
on:
  workflow_run:
    # Preveri, če je Test workflow bil uspešen
    workflows: ["Test Workflow"]
    types:
      - completed

jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Zgradi Docker Image
      - name: Build and push Docker image
        run: |
          chmod +x zapakiraj_27115.sh
          ./zapakiraj_27115.sh
