name: Test Workflow
on:
  push:
    branches:
      - main

jobs:
  check-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Check if test scripts exist
        run: |
          if [ ! -d "tests" ]; then
            echo "Test scripts directory not found" > napaka.txt
            exit 1
          fi
        
      - name: Prepare test environment
        run: |
          # Setup test environment here
        
      - name: Run tests
        run: |
          # Run tests here
        
      - name: Store artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests/results
  
  handle-error:
    runs-on: ubuntu-latest
    needs: check-tests
    if: failure()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Read error file
        run: cat napaka.txt

